SELECT [ProductID]
      ,[Name]
      ,[ProductNumber]
      ,[MakeFlag]
      ,[FinishedGoodsFlag]
      ,[StandardCost]
      ,[ListPrice]
      ,[ProductSubcategoryID]
      ,[ProductModelID]
      ,[Color]
      ,[SafetyStockLevel]
      ,[ReorderPoint]
      ,[Size]
      ,[SizeUnitMeasureCode]
      ,[WeightUnitMeasureCode]
      ,[Weight]
      ,[DaysToManufacture]
      ,[Style]
      ,[ProductLine]
      ,[Class]
      ,[SellStartDate]
      ,[SellEndDate]
      ,[DiscontinuedDate]
      ,[rowguid]
      ,[ModifiedDate]
  FROM [CompanyX].[Production].[Product]
  --where ProductID = 328
  --where FinishedGoodsFlag = 0 and StandardCost <> 0
  order by FinishedGoodsFlag